### ISSUE TITLE
cmd_add and cmd_rebase not implemented?

### ISSUE THREAD

**Issue by shauryashaurya** [thblt/write-yourself-a-git#15]
Brilliant effort, I have just started on this today, but was a bit surprised to see that some commands like add and rebase are not around, maybe I am missing something?

**Comment by thblt** [comment]
Hey thanks for your feedback.  No, the whole staging area/commit infrastructure is not done yet, it'll be written when I find the time (or if someone else feels like contributing the missing sections).  Same for rebase, although rebase is way easier provided you simplify it to the point where you just change the parent of a commit.

**Comment by thblt** [comment]
Done (except rebase, but it's trivial)
