### ISSUE TITLE
Implement staging area/status/commit

### ISSUE THREAD

**Issue by thblt** [thblt/write-yourself-a-git#17]
The staging area remains to be implemented. It's not hard, but it's tedious. The main difficulty is that it's it's not just a stupid tree object (for performance reasons) but the “index file”,  whose format is documented here: https://github.com/git/git/blob/master/Documentation/technical/index-format.txt. Also it's a binary file, which is the kind of format where C shines and Python, well, shines a bit less.

**Comment by cutebbb** [comment]
Maybe we can start with the `ls-files` command. And I've made a PR for it;
