### ISSUE TITLE
In the Windows warning, alert users to line-ending issue

### ISSUE THREAD

**Issue by bhagerty** [thblt/write-yourself-a-git#28]
Windows users using WSL might benefit from a warning about needing to use Unix-style line endings. The website, but not the source (that I could see), includes a "Warning" to Windows users. I would suggest revising it along these lines:

`wyag` should run on any Unix-like system with a Python interpreter, but I have absolutely no idea how it will behave on Windows. The test suite absolutely requires a bash-compatible shell, which WSL can provide. Also, if you are using WSL, make sure your `wyag` file uses Unix-style line endings ([see StackOverflow if you use VS Code](https://stackoverflow.com/questions/48692741/how-can-i-make-all-line-endings-eols-in-all-files-in-visual-studio-code-unix)). Feedback from Windows users would be appreciated!

**Comment by thblt** [comment]
Thanks!
