### ISSUE TITLE
Parsing trees may cause a bug?

### ISSUE THREAD

**Issue by qianqianShallow** [thblt/write-yourself-a-git#34]
hello, the current code in def tree_parse_one(raw, start=0) as followed:
 ```
sha = hex(
        int.from_bytes(
            raw[y+1:y+21], "big"))[2:] 
```
but if sha have a leading 0，it may cause a bug?

**Comment by thblt** [comment]
My mistake, this was fixed in e3062924670c3313dcfb46bf8e3b8cf2e2d55321, but the fix hasn't been uploaded. Thanks!

**Comment by qianqianShallow** [comment]
Sorry, i did not notice it! I found the code in a blog and the code in blog seem not be updated. However, the code is very helpful for me, it help me understand the git, thanks!

**Comment by thblt** [comment]
> I found the code in a blog and the code in blog seem not be updated. 

It should be now!
