### ISSUE TITLE
Formatting/render error

### ISSUE THREAD

**Issue by daveloyall** [thblt/write-yourself-a-git#5]
Hello.  Neat document, thanks!

When I look at this line on https://wyag.thb.lt/, the word "find" is rendered as subscript.  I think the underscore needs to be escaped.

https://github.com/thblt/write-yourself-a-git/blame/f8fe10478406453b1e1c3890545a38cdd8f1644e/write-yourself-a-git.org#L574

**Comment by thblt** [comment]
Thanks!
