### ISSUE TITLE
Inconsistency in configuration file description

### ISSUE THREAD

**Issue by jgbishop** [thblt/write-yourself-a-git#6]
The code for setting up the configuration file (section 3.1) has this line:

    ret.set("core", "filemode", "false")

But the bulleted list just above this block has `filemode = true` which seems inconsistent to me. Which is required here: true or false?

**Comment by Naman-Bhalla** [comment]
I guess it should be filemode = false. As it needs to disable the tracking of files in worktree.
By default, git also has it as false I guess:

> ; core variables
> [core]
> 	; Don't trust file modes
> 	filemode = false

**Comment by thblt** [comment]
Thanks!
